services:
  mysql:
    image: mysql:8.0.27
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - ./db/mysql/data:/var/lib/mysql
      # - ./db/mysql/init:/docker-entrypoint-initdb.d/mysql-init.sql
