spring:
  application:
    name: ourdressingtable
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  profiles:
    active: local
    group:
      local:
        - db-local
      dev:
        - db-dev
      prod:
        - db-prod
    include:
      - db
      # - site
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  logging:
    level:
      root: debug

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  logging:
    level:
      root: info
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
  logging:
    level:
      root: warn
