spring:
  application:
    name: ourdressingtable

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  config:
    import:
      - classpath:application-db.yml


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # swagger ?? ?? ??!

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace